/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchOldRouteImport } from './routes/search-old'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RandomRouteImport } from './routes/random'
import { Route as IndexRouteImport } from './routes/index'

const SearchOldRoute = SearchOldRouteImport.update({
  id: '/search-old',
  path: '/search-old',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/random': typeof RandomRoute
  '/search': typeof SearchRoute
  '/search-old': typeof SearchOldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/random': typeof RandomRoute
  '/search': typeof SearchRoute
  '/search-old': typeof SearchOldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/random': typeof RandomRoute
  '/search': typeof SearchRoute
  '/search-old': typeof SearchOldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/random' | '/search' | '/search-old'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/random' | '/search' | '/search-old'
  id: '__root__' | '/' | '/random' | '/search' | '/search-old'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RandomRoute: typeof RandomRoute
  SearchRoute: typeof SearchRoute
  SearchOldRoute: typeof SearchOldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search-old': {
      id: '/search-old'
      path: '/search-old'
      fullPath: '/search-old'
      preLoaderRoute: typeof SearchOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RandomRoute: RandomRoute,
  SearchRoute: SearchRoute,
  SearchOldRoute: SearchOldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
